server:
  port: 8083
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启feign对sentinel的支持
cc:
  swagger:
    title: 购物车服务接口文档
    package: com.hmall.cart.controller
  db:
    database: cc-cart
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090  #sentinel控制台地址
      http-method-specify: true # 开启请求方式前缀